In [2]:

### Benjamin Tollison ###
import sympy as sp
from IPython.display import display, Math, Latex
from sympy.solvers.solveset import linsolve
from sympy.solvers.pde import pdsolve
from sympy import  lambdify, Matrix,sin,cos, sinh, cosh, exp, pi, symbols, integrate, Function, Eq
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy
def displayEquations(LHS,RHS):
    left = sp.latex(LHS)
    right = sp.latex(RHS)
    display(Math(left + '=' + right))
    np.set_printoptions(suppress=True)
def displayVariable(variable:str,RHS):
    left = sp.latex(symbols(variable))
    right = sp.latex(RHS)
    display(Math(left + '=' + right))
def displayVariableWithUnits(variable:str,RHS,units):
    left = sp.latex(symbols(variable))
    right = sp.latex(RHS)
    latexUnit = sp.latex(symbols(units))
    display(Math(left + '=' + right + '\\;' +'\\left['+ latexUnit + '\\right]'))

In [8]:
import numpy as np
def ParenthesisModulo(value,modulus):
  iteration = 0
  for i in range(int(modulus**0.5),modulus+1):
    iteration+=1
    if value*i%modulus == 1:
      return i
    if iteration == modulus:
      print('There is no inverse')
      return False
def ModuloInverse(value,upperlimit):
  for i in range(upperlimit,0,-1):
    if np.gcd(value,i)==1:
      return i
    elif i == 1:
      print('% Inverse error')
      return False
def prime_factors(n):
  i = 2
  factors = []
  while i * i <= n:
      if n % i:
          i += 1
      else:
          n //= i
          factors.append(i)
  if n > 1:
      factors.append(n)
  return factors

In [125]:
N = 539873
smoothness = 100
intial_guess = int(N**0.5)
quadratic_sieve_dict = {}
for i in range(smoothness):
  number_to_factor_check = intial_guess**2%N
  if len(prime_factors(number_to_factor_check)) != 0 and prime_factors(number_to_factor_check)[-1] <= 17:
    quadratic_sieve_dict.__setitem__(str(number_to_factor_check),list(prime_factors(number_to_factor_check)))
  intial_guess+=1
possible_prime_factors=[int(prime) for prime in list(quadratic_sieve_dict.keys())]
prime_factors_list = [2, 3, 5, 7, 11, 13, 17]
A_matrix = np.zeros((len(prime_factors_list),len(prime_factors_list)))
iteration = 0
for key in quadratic_sieve_dict.keys():
  dict_of_counts = {i:quadratic_sieve_dict[key].count(i) for i in quadratic_sieve_dict[key]}
  for key in dict_of_counts.keys():
    for i,value in enumerate(prime_factors_list):
      if key == value:
        A_matrix[iteration][i] = dict_of_counts.get(key)
  iteration += 1
A_matrix = A_matrix[~np.all(A_matrix==0,axis=1)]
A_matrix = A_matrix.T
A_matrix = A_matrix[~np.all(A_matrix==0,axis=1)]
print(A_matrix)
b_array = np.zeros(len(A_matrix[0]))
solution_exponents = np.linalg.solve(A_matrix,b_array.T)
print(solution_exponents)
# U,S,Vh = np.linalg.svd(A_matrix)
# print(S)
# print(np.linalg.eig(A_matrix))
# print(np.dot(A_matrix,2*Vh[-1]))
solution_exponents = np.array([1,0,0,1])
for i,value in enumerate(solution_exponents):
  if value !=0:
    

[[5. 0. 9. 5.]
 [1. 3. 1. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 2.]]
[0. 0. 0. 0.]
0
1
2
3


In [123]:

N = 342647387528779375670375098162296213741958911642475645613557064143782
smoothness = 100
intial_guess = int(N**0.5)
quadratic_sieve_dict = {}
for i in range(smoothness):
  number_to_factor_check = intial_guess**2%N
  if len(prime_factors(number_to_factor_check)) != 0 and prime_factors(number_to_factor_check)[-1] <= 17:
    quadratic_sieve_dict.__setitem__(str(number_to_factor_check),list(prime_factors(number_to_factor_check)))
  intial_guess+=1
  print(number_to_factor_check)
possible_prime_factors=[int(prime) for prime in list(quadratic_sieve_dict.keys())]
prime_factors_list = [2, 3, 5, 7, 11, 13, 17]
A_matrix = np.zeros((len(prime_factors_list),len(prime_factors_list)))
# A_matrix = np.zeros((len(possible_prime_factors),len(possible_prime_factors)))
iteration = 0
for key in quadratic_sieve_dict.keys():
  dict_of_counts = {i:quadratic_sieve_dict[key].count(i) for i in quadratic_sieve_dict[key]}
  for key in dict_of_counts.keys():
    for i,value in enumerate(prime_factors_list):
      if key == value:
        A_matrix[iteration][i] = dict_of_counts.get(key)
  iteration += 1
A_matrix = A_matrix[~np.all(A_matrix==0,axis=1)]
A_matrix = A_matrix.T
A_matrix = A_matrix[~np.all(A_matrix==0,axis=1)]
print(A_matrix)
x_array = np.zeros(len(A_matrix[0]))
solution_exponents = np.linalg.solve(A_matrix,x_array)
print(solution_exponents)

KeyboardInterrupt: 