In [93]:
### Benjamin Tollison ###
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy
import sympy as sp
from IPython.display import Latex, Math, display
from sympy import (
    Eq,
    Function,
    Matrix,
    cos,
    cosh,
    exp,
    integrate,
    lambdify,
    pi,
    sin,
    sinh,
    symbols,
)
from decimal import Decimal
from sympy.solvers.pde import pdsolve
from sympy.solvers.solveset import linsolve
def displayEquations(LHS,RHS):
    left = sp.latex(LHS)
    right = sp.latex(RHS)
    display(Math(left + '=' + right))
    np.set_printoptions(suppress=True)
def displayVariable(variable:str,RHS):
    left = sp.latex(symbols(variable))
    right = sp.latex(RHS)
    display(Math(left + '=' + right))
def displayVariableWithUnits(variable:str,RHS,units):
    left = sp.latex(symbols(variable))
    right = sp.latex(RHS)
    latexUnit = sp.latex(symbols(units))
    display(Math(left + '=' + right + '\\;' +'\\left['+ latexUnit + '\\right]'))
def format_scientific(number:float):
    a = '%E' % number
    return a.split('E')[0].rstrip('0').rstrip('.') + 'E' + a.split('E')[1]
deg2rad = np.pi/180
rad2deg = 180/np.pi

### Setting the Globals based off of my information

In [94]:
astro_constants = pd.read_csv('AstroConstants.csv')
ephemeris = pd.read_csv('EphemerisData.csv')
x = 20
y = 4
earth_parking_radius = 10*x + 450 + astro_constants['Earth'][1]   # km
mars_periapsis_radius = 15*y +150 + astro_constants['Mars'][1]
mars_apoapsis_radius = 275*y + 2500 + astro_constants['Mars'][1]
def GetIndexFromList(list, target_value):
    for key, value in enumerate(list):
        if value == target_value:
            return key
departure_index = GetIndexFromList(ephemeris['Epoch'],'10-Nov-26')
departure_data = {key:value[departure_index] for key,value in ephemeris.items()}
mu_sun = astro_constants['Sun'][0]
mu_earth = astro_constants['Earth'][0]
mu_mars = astro_constants['Mars'][0]
unit_length_conversion = astro_constants['Earth'][3]
unit_time_conversion = np.sqrt(unit_length_conversion**3/mu_sun) # sec
print(unit_length_conversion,'km')
print(unit_time_conversion,'seconds')
print(unit_time_conversion/(60*60*24),'days')
print(mu_sun,unit_length_conversion**3/unit_time_conversion**2)
display(pd.DataFrame(ephemeris))
display(pd.DataFrame(departure_data,index=[departure_index]))
print(departure_data['Earth X'])

149597870.7 km
5022642.890913032 seconds
58.132440867048985 days
132712440041.9393 132712440041.93929


Epoch       Earth X       Earth Y      Earth Z  Earth Xdot  \
0      1-Apr-26 -1.467589e+08 -2.596065e+07 -11252418.52    5.156136   
1      2-Apr-26 -1.462918e+08 -2.828332e+07 -12259161.90    5.656401   
2      3-Apr-26 -1.457815e+08 -3.059764e+07 -13262298.92    6.154717   
3      4-Apr-26 -1.452283e+08 -3.290298e+07 -14261557.55    6.651050   
4      5-Apr-26 -1.446323e+08 -3.519869e+07 -15256664.17    7.145344   
...         ...           ...           ...          ...         ...   
1386  16-Jan-30 -6.328359e+07  1.218936e+08  52837760.35  -27.366695   
1387  17-Jan-30 -6.563809e+07  1.208502e+08  52385597.19  -27.134269   
1388  18-Jan-30 -6.797217e+07  1.197695e+08  51917241.86  -26.894022   
1389  19-Jan-30 -7.028516e+07  1.186517e+08  51432840.00  -26.646065   
1390  20-Jan-30 -7.257639e+07  1.174973e+08  50932538.00  -26.390484   

      Earth Ydot  Earth Zdot       Mars X       Mars Y       Mars Z  \
0     -26.928642  -11.671947  193782670.7 -63169669.47 -34201020.13   
1     -26.835687  -11.631776  194577093.9 -61210155.93 -33323663.26   
2     -26.735375  -11.588464  195349683.9 -59243774.59 -32442567.40   
3     -26.627694  -11.541995  196100359.1 -57270747.61 -31557832.24   
4     -26.512620  -11.492349  196829040.8 -55291297.98 -30669557.95   
...          ...         ...          ...          ...          ...   
1386  -11.858771   -5.139106  201863133.8 -39278038.74 -23459454.69   
1387  -12.293109   -5.327355  202390561.9 -37250983.41 -22543907.75   
1388  -12.723439   -5.513923  202895391.9 -35219768.54 -21625843.54   
1389  -13.149733   -5.698801  203377580.7 -33184623.24 -20705366.00   
1390  -13.571978   -5.881981  203837088.6 -31145776.88 -19782579.26   

      Mars Xdot  Mars Ydot  Mars Zdot  
0      9.320738  22.638956  10.132573  
1      9.068525  22.719727  10.176423  
2      8.815347  22.797931  10.219122  
3      8.561242  22.873559  10.260665  
4      8.306246  22.946602  10.301046  
...         ...        ...        ...  
1386   6.235094  23.436334  10.581640  
1387   5.973802  23.485802  10.611376  
1388   5.711994  23.532619  10.639910  
1389   5.449707  23.576783  10.667240  
1390   5.186979  23.618291  10.693363  

[1391 rows x 13 columns]

Epoch      Earth X      Earth Y      Earth Z  Earth Xdot  Earth Ydot  \
223  10-Nov-26  100622923.6  99795464.56  43259105.48  -22.360161   18.463842   

     Earth Zdot       Mars X       Mars Y      Mars Z  Mars Xdot  Mars Ydot  \
223    8.003854 -60800396.04  210334752.7  98115468.4 -22.520655  -3.932676   

     Mars Zdot  
223  -1.196445

100622923.6


In [95]:
def Alpha(a,s):
  return  2*np.arcsin(np.sqrt(s/(2*a)))
def alphaPrime(a,s):
  x_squared = s/(2*a)
  dx = (-1/2)*np.sqrt(s/(2*a**3))
  return dx/np.sqrt(1-x_squared)
def Beta(a,s,c):
  return 2*np.arcsin(np.sqrt((s-c)/(2*a)))
def betaPrime(a,s,c):
  x_squared = (s-c)/(2*a)
  dx = (-1/2)*np.sqrt((s-c)/(2*a**3))
  return dx/np.sqrt(1-x_squared)
def P_transfer(a,s,r1,r2,c,alphabeta):
  p = ((4*a*(s-r1)*(s-r2))/c**2)*np.sin((alphabeta)/2)
  return p
def LambertFunction(a,alpha,beta,non_dimensional_TOF):
  return np.sqrt(a**3)*(alpha-beta -(np.sin(alpha)-np.sin(beta))) - non_dimensional_TOF
def LambertFunctionPrime(a,alpha,alphaprime,beta,betaprime):
  return (3/2)*np.sqrt(a)*(alphaprime-betaprime -(alphaprime*np.cos(alpha)-betaprime*np.cos(beta))) 
def OneATransfer(a0,s,c,non_dimensional_TOF):
  alpha = Alpha(a0,s)
  beta = Beta(a0,s,c)
  alphaprime = alphaPrime(a0,s)
  betaprime = betaPrime(a0,s,c)
  iteration_max = 1000
  while iteration_max !=0:
    lambert = LambertFunction(a0,alpha,beta,non_dimensional_TOF)
    lambertprime = LambertFunctionPrime(a0,alpha,alphaprime,beta,betaprime)
    # print(lambert)
    if abs(lambert) < 1e-4:
      # print(a0)
      return a0
    elif iteration_max == 0:
      return print('method didnt converge')
    else:
      a0 = a0 + lambert/lambertprime
      iteration_max -= 1
      # print(iteration_max)
def OneBTransfer(a0,s,c,non_dimensional_TOF):
  alpha = 2*np.pi - Alpha(a0,s)
  beta = Beta(a0,s,c)
  alphaprime = alphaPrime(a0,s)
  betaprime = betaPrime(a0,s,c)
  iteration_max = 1000
  while iteration_max !=0:
    lambert = LambertFunction(a0,alpha,beta,non_dimensional_TOF)
    lambertprime = LambertFunctionPrime(a0,alpha,alphaprime,beta,betaprime)
    # print(lambert)
    if abs(lambert) < 1e-4:
      # print(a0)
      return a0
    elif iteration_max == 0:
      return print('method didnt converge')
    else:
      a0 = a0 + lambert/lambertprime
      iteration_max -= 1
      # print(iteration_max)
def TwoATransfer(a0,s,c,non_dimensional_TOF):
  alpha = Alpha(a0,s)
  beta = -Beta(a0,s,c)
  alphaprime = alphaPrime(a0,s)
  betaprime = betaPrime(a0,s,c)
  iteration_max = 1000
  while iteration_max !=0:
    lambert = LambertFunction(a0,alpha,beta,non_dimensional_TOF)
    lambertprime = LambertFunctionPrime(a0,alpha,alphaprime,beta,betaprime)
    # print(lambert)
    if abs(lambert) < 1e-4:
      # print(f'a_2a={a0}')
      return a0
    elif iteration_max == 0:
      return print('method didnt converge')
    else:
      a0 = a0 + lambert/lambertprime
      iteration_max -= 1
      # print(iteration_max)
def TwoBTransfer(a0,s,c,non_dimensional_TOF):
  alpha = 2*np.pi - Alpha(a0,s)
  beta = -Beta(a0,s,c)
  alphaprime = alphaPrime(a0,s)
  betaprime = betaPrime(a0,s,c)
  iteration_max = 1000
  while iteration_max !=0:
    lambert = LambertFunction(a0,alpha,beta,non_dimensional_TOF)
    lambertprime = LambertFunctionPrime(a0,alpha,alphaprime,beta,betaprime)
    # print(lambert)
    if abs(lambert) < 1e-4:
      # print(a0)
      return a0
    elif iteration_max == 0:
      return print('method didnt converge')
    else:
      a0 = a0 + lambert/lambertprime
      iteration_max -= 1
      # print(iteration_max)
  return print('TODO 2B')
def EllipticTransfer(s,c,non_dimensional_TOF,TOF_p1,TOF_p2):
  a_min = 0.5*s
  alpha_min = Alpha(a_min,s)
  beta_min = Beta(a_min,s,c)
  TOFm1 = np.sqrt(a_min**3/1)*((alpha_min - np.sin(alpha_min)) - (beta_min-np.sin(beta_min)))
  TOFm2 = np.sqrt(a_min**3/1)*((alpha_min - np.sin(alpha_min)) + (beta_min-np.sin(beta_min)))
  a0 = a_min + 1e-4
  a_transfers = [0,0,0,0]
  if TOF_p1 < non_dimensional_TOF and non_dimensional_TOF < TOFm1:
    a_t1a = OneATransfer(a0,s,c,non_dimensional_TOF)
    a_transfers[0] = a_t1a
  if TOFm1 < non_dimensional_TOF:
    a_t1b = OneBTransfer(a0,s,c,non_dimensional_TOF)
    a_transfers[1] = a_t1b
  if TOF_p2 < non_dimensional_TOF and non_dimensional_TOF < TOFm2:
    a_t2a = TwoATransfer(a0,s,c,non_dimensional_TOF)
    a_transfers[2] = a_t2a
  if TOFm2 < non_dimensional_TOF:
    a_t2b = TwoBTransfer(a0,s,c,non_dimensional_TOF)
    a_transfers[3] = a_t2b
  return a_transfers
def HyperbolicTransfer():
  return print('TODO Hyperbolic')
def F(r2,p,delta_f):
  return 1 - (r2/p)*(1-np.cos(delta_f))
def G(r1,r2,p,delta_f):
  return ((r1*r2)/np.sqrt(p))*np.sin(delta_f)
def G_dot(r1,p,delta_f):
  return 1 - (r1/p)*(1-np.cos(delta_f))
def F_dot(r1,r2,p,delta_f):
  return (F(r2,p,delta_f)*G_dot(r1,p,delta_f)-1)/G(r1,r2,p,delta_f)

In [98]:
def LamberSolverA(TOF):
  arrival_index = departure_index + TOF
  arrival_data = {key:value[arrival_index] for key,value in ephemeris.items()}
  r1_vec = np.array([departure_data['Earth X'],departure_data['Earth Y'],departure_data['Earth Z']])/unit_length_conversion
  r2_vec = np.array([arrival_data['Earth X'],arrival_data['Earth Y'],arrival_data['Earth Z']]) /unit_length_conversion
  c_vec = r2_vec - r1_vec
  v_earth = np.array([departure_data['Earth Xdot'],departure_data['Earth Ydot'],departure_data['Earth Zdot']])
  v_mars = np.array([arrival_data['Mars Xdot'],arrival_data['Mars Ydot'],arrival_data['Mars Zdot']])
  print(v_mars)
  r1,r2,c = np.linalg.norm(r1_vec),np.linalg.norm(r2_vec),np.linalg.norm(c_vec)
  s = 0.5*(r1+r2+c)
  non_dimensional_TOF = (TOF*24*3600)/unit_time_conversion
  TOF_p1 = (1/3)*np.sqrt(2/1)*(s**(3/2) - (s-c)**(3/2))
  TOF_p2 = (1/3)*np.sqrt(2/1)*(s**(3/2) + (s-c)**(3/2))
  if non_dimensional_TOF < TOF_p1 or non_dimensional_TOF <= TOF_p2:
    HyperbolicTransfer()
  if non_dimensional_TOF > TOF_p2:
    transfer_velocities = {'v1':[],'v2':[]}
    p_t = []
    J = []
    display(EllipticTransfer(s,c,non_dimensional_TOF,TOF_p1,TOF_p2))
    index = 0
    for a_t in EllipticTransfer(s,c,non_dimensional_TOF,TOF_p1,TOF_p2):
      if a_t != 0:
        alphabeta = Alpha(a_t,s) + Beta(a_t,s,c)*(-1)**(index+2)
        p_t.append(P_transfer(a_t,s,r1,r2,c,alphabeta))
        p = P_transfer(a_t,s,r1,r2,c,alphabeta)
        if index <= 1:
          deltaf = np.arccos(np.dot(r1_vec,r2_vec)/(r1*r2))
          v1t = (1/G(r1,r2,p,deltaf))*(r2_vec-F(r2,p,deltaf)*r1_vec)
          v2t = F_dot(r1,r2,p,deltaf)*r1_vec + G_dot(r1,p,deltaf)*v1t
          transfer_velocities['v1'].append(v1t),transfer_velocities['v2'].append(v2t)
        else:
          deltaf = np.pi - np.arccos(np.dot(r1_vec,r2_vec)/(r1*r2))
          v1t = (1/G(r1,r2,p,deltaf))*(r2_vec-F(r2,p,deltaf)*r1_vec)
          v2t = F_dot(r1,r2,p,deltaf)*r1_vec + G_dot(r1,p,deltaf)*v1t
          transfer_velocities['v1'].append(v1t),transfer_velocities['v2'].append(v2t)
      else:
        p_t.append(0.0)
      index +=1
    if not np.isnan(transfer_velocities['v1'][0][0]):
      for i in range(2):
        J_i = (np.linalg.norm(transfer_velocities['v1'][i]-v_earth)) + (np.linalg.norm(transfer_velocities['v2'][i]-v_mars))
        J.append(J_i)
      print(J) 
    else:
      print("The value is NaN.")
      return None
    return print('TODO LamberSolverA')
for days in range(100,701):
  LamberSolverA(days)

[-11.33014309 -17.24157556  -7.60280041]


[0.6847635152839586, 0, 0.6664649808575551, 0]

The value is NaN.
[-11.17037639 -17.32427381  -7.64504179]


C:\Users\benja\AppData\Local\Temp\ipykernel_20592\216515559.py:2: RuntimeWarning: invalid value encountered in arcsin
  return  2*np.arcsin(np.sqrt(s/(2*a)))


[0.6889086229746878, 0, 0.6712664108898311, 0]

The value is NaN.
[-11.00993371 -17.40584102  -7.6867826 ]


[0.6930474233575298, 0, 0.6760469123963203, 0]

The value is NaN.
[-10.84882281 -17.48627395  -7.72802115]


[0.6971799840740353, 0, 0.6808051837460325, 0]

The value is NaN.
[-10.68705144 -17.5655694   -7.76875577]


[0.7013063700575655, 0, 0.685542986588005, 0]

The value is NaN.
[-10.52462735 -17.64372419  -7.80898478]


[0.7054266444381584, 0, 0.6902590221943262, 0]

The value is NaN.
[-10.3615583  -17.72073512  -7.84870651]


[0.7095408691410832, 0, 0.6949550409584322, 0]

The value is NaN.
[-10.19785203 -17.79659904  -7.88791931]


[0.7136483547778517, 0, 0.6996297459133073, 0]

The value is NaN.
[-10.03351631 -17.8713128   -7.92662152]


[0.7177506594212896, 0, 0.7042848744715887, 0]

The value is NaN.
[ -9.86855888 -17.94487326  -7.9648115 ]


[0.721847093547985, 0, 0.7089191323677433, 0]

The value is NaN.
[ -9.70298749 -18.01727731  -8.00248759]


[0.7259377140994201, 0, 0.7135342439701133, 0]

The value is NaN.
[ -9.53680991 -18.08852184  -8.03964818]


[0.7300225761399456, 0, 0.7181289196449957, 0]

The value is NaN.
[ -9.37003388 -18.15860376  -8.07629163]


[0.7341017326441691, 0, 0.7227048709469392, 0]

The value is NaN.
[ -9.20266718 -18.22751998  -8.11241631]


[0.7381744892262021, 0, 0.727260814634134, 0]

The value is NaN.
[ -9.03471756 -18.29526743  -8.14802062]


[0.7422423813776157, 0, 0.7317984492642208, 0]

The value is NaN.
[ -8.86619279 -18.36184306  -8.18310293]


[0.746304713326081, 0, 0.7363172426566389, 0]

The value is NaN.
[ -8.69710066 -18.42724382  -8.21766165]


[0.7503615289990749, 0, 0.7408166498469739, 0]

The value is NaN.
[ -8.52744894 -18.49146669  -8.25169517]


[0.7544128699926491, 0, 0.7452983714193836, 0]

The value is NaN.
[ -8.35724541 -18.55450864  -8.2852019 ]


[0.7584580350237565, 0, 0.7497611230627623, 0]

The value is NaN.
[ -8.18649787 -18.61636666  -8.31818025]


[0.7624985382448016, 0, 0.754206590642777, 0]

The value is NaN.
[ -8.01521411 -18.67703776  -8.35062862]


[0.7665336771613144, 0, 0.7586335007169105, 0]

The value is NaN.
[ -7.84340196 -18.73651895  -8.38254545]


[0.7705634835428584, 0, 0.7630435238682038, 0]

The value is NaN.
[ -7.67106922 -18.79480725  -8.41392915]


[0.7745872527744191, 0, 0.7674361300421737, 0]

The value is NaN.
[ -7.49822372 -18.85189969  -8.44477815]


[0.7786064745296648, 0, 0.7718107809069806, 0]

The value is NaN.
[ -7.32487329 -18.90779334  -8.4750909 ]


[0.7826204423884251, 0, 0.7761691454712569, 0]

The value is NaN.
[ -7.15102579 -18.96248523  -8.50486582]


[0.7866291768295007, 0, 0.780510691813265, 0]

The value is NaN.
[ -6.97668907 -19.01597244  -8.53410135]


[0.7906326954471957, 0, 0.7848348818397477, 0]

The value is NaN.
[ -6.801871   -19.06825205  -8.56279596]


[0.7946302819788871, 0, 0.7891433809372294, 0]

The value is NaN.
[ -6.62657947 -19.11932114  -8.59094808]


[0.79862340668913, 0, 0.793435657165673, 0]

The value is NaN.
[ -6.45082236 -19.1691768   -8.61855617]


[0.8026113519976925, 0, 0.7977111744609107, 0]

The value is NaN.
[ -6.27460759 -19.21781616  -8.64561869]


[0.8065941252356893, 0, 0.8019715912663274, 0]

The value is NaN.
[ -6.09794308 -19.26523631  -8.67213411]


[0.8105710079524173, 0, 0.806216376552995, 0]

The value is NaN.
[ -5.92083678 -19.3114344   -8.6981009 ]


[0.8145434481495564, 0, 0.8104449970321929, 0]

The value is NaN.
[ -5.74329662 -19.35640755  -8.72351752]


[0.818510728208583, 0, 0.8146590991720869, 0]

The value is NaN.
[ -5.56533059 -19.40015291  -8.74838245]


[0.8224728497494469, 0, 0.8188581527971882, 0]

The value is NaN.
[ -5.38694667 -19.44266764  -8.77269417]


[0.8264298135231781, 0, 0.8230416276417613, 0]

The value is NaN.
[ -5.20815288 -19.48394891  -8.79645117]


[0.830380901212013, 0, 0.8272111526557198, 0]

The value is NaN.
[ -5.02895722 -19.52399388  -8.81965194]


[0.8343275453709555, 0, 0.8313661994459127, 0]

The value is NaN.
[ -4.84936774 -19.56279974  -8.84229496]


[0.8382690287137672, 0, 0.8355069551718047, 0]

The value is NaN.
[ -4.66939252 -19.60036369  -8.86437873]


[0.8422053479768624, 0, 0.8396328896048906, 0]

The value is NaN.
[ -4.48903962 -19.63668293  -8.88590175]


[0.8461364985786616, 0, 0.8437456163274842, 0]

The value is NaN.
[ -4.30831716 -19.67175467  -8.90686252]


[0.8500624745226086, 0, 0.8478446065947179, 0]

The value is NaN.
[ -4.12723326 -19.70557613  -8.92725955]


[0.853983268323543, 0, 0.8519300431384988, 0]

The value is NaN.
[ -3.94579606 -19.73814455  -8.94709135]


[0.8578981599224996, 0, 0.8560021077904042, 0]

The value is NaN.
[ -3.76401375 -19.76945716  -8.96635644]


[0.8618085598117533, 0, 0.8600609815456468, 0]

The value is NaN.
[ -3.58189451 -19.79951123  -8.98505333]


[0.8657137460675989, 0, 0.8641061363025272, 0]

The value is NaN.
[ -3.39944656 -19.828304    -9.00318054]


[0.8696137048358257, 0, 0.8681391672462031, 0]

The value is NaN.
[ -3.21667816 -19.85583276  -9.02073661]


[0.8735084205481083, 0, 0.8721595461870013, 0]

The value is NaN.
[ -3.03359757 -19.88209478  -9.03772005]


[0.8773978758480491, 0, 0.8761674512282194, 0]

The value is NaN.
[ -2.85021308 -19.90708735  -9.05412942]


[0.8812820515077052, 0, 0.8801630598509678, 0]

The value is NaN.
[ -2.66653304 -19.93080777  -9.06996323]


[0.8851609263369243, 0, 0.884146548973868, 0]

The value is NaN.
[ -2.48256577 -19.95325337  -9.08522004]


[0.8890344771048462, 0, 0.8881180950097142, 0]

The value is NaN.
[ -2.29831968 -19.97442145  -9.09989839]


[0.8929026784829107, 0, 0.8920778739221492, 0]

The value is NaN.
[ -2.11380317 -19.99430936  -9.11399683]


[0.8967655030255495, 0, 0.8960267599904401, 0]

The value is NaN.
[ -1.92902468 -20.01291443  -9.12751392]


[0.900623615605346, 0, 0.8999635265782895, 0]

The value is NaN.
[ -1.74399269 -20.03023402  -9.14044821]


[0.9044755903205863, 0, 0.9038890507712096, 0]

The value is NaN.
[ -1.5587157  -20.04626551  -9.15279827]


[0.90832209264326, 0, 0.9078035070328151, 0]

The value is NaN.
[ -1.37320224 -20.06100626  -9.16456266]


[0.912163087113804, 0, 0.9117070694941358, 0]

The value is NaN.
[ -1.18746088 -20.07445368  -9.17573996]


[0.9159992245158984, 0, 0.9156006005344852, 0]

The value is NaN.
[ -1.00150023 -20.08660515  -9.18632875]


[0.9198290801882587, 0, 0.9194828867722924, 0]

The value is NaN.
[ -0.81532893 -20.09745809  -9.19632759]


[0.9236539987143864, 0, 0.9233554876124561, 0]

The value is NaN.
[ -0.62895563 -20.10700994  -9.20573509]


[0.927472548403799, 0, 0.9272171847562048, 0]

The value is NaN.
[ -0.44238906 -20.11525813  -9.21454984]


[0.931286068186669, 0, 0.9310695346454115, 0]

The value is NaN.
[ -0.25563795 -20.12220012  -9.22277042]


[0.9350931312052154, 0, 0.9349113261289617, 0]

The value is NaN.
[ -0.06871108 -20.12783336  -9.23039545]


[0.9388950574556116, 0, 0.9387440993465187, 0]

The value is NaN.
[  0.11838274 -20.13215534  -9.23742352]


[0.9426911091715381, 0, 0.9425673357465881, 0]

The value is NaN.
[  0.30563464 -20.13516356  -9.24385325]


[0.9464812287198203, 0, 0.9463811992611322, 0]

The value is NaN.
[  0.49303574 -20.13685551  -9.24968326]


[0.9502653556398138, 0, 0.950185852704874, 0]

The value is NaN.
[  0.6805771  -20.13722871  -9.25491217]


[0.954044100774796, 0, 0.9539821326036104, 0]

The value is NaN.
[  0.86824976 -20.13628071  -9.25953861]


[0.9578160354030261, 0, 0.9577688361312079, 0]

The value is NaN.
[  1.0560447  -20.13400904  -9.2635612 ]


[0.9615824358571742, 0, 0.9615474698705152, 0]

The value is NaN.
[  1.24395287 -20.13041127  -9.26697859]


[0.9653425366123417, 0, 0.9653174991308467, 0]

The value is NaN.
[  1.43196516 -20.12548497  -9.26978943]


[0.9690969082331276, 0, 0.969079728489098, 0]

The value is NaN.
[  1.62007245 -20.11922773  -9.27199235]


[0.9728447532060126, 0, 0.9728335961594176, 0]

The value is NaN.
[  1.80826554 -20.11163715  -9.27358601]


[0.9765859190522019, 0, 0.9765791883478289, 0]

The value is NaN.
[  1.9965352  -20.10271086  -9.27456907]


[0.9803215507976656, 0, 0.9803178916022673, 0]

The value is NaN.
[  2.18487214 -20.09244648  -9.2749402 ]


[0.9840500069528277, 0, 0.9840483080341108, 0]

The value is NaN.
[  2.37326704 -20.08084167  -9.27469806]


[0.9877721612779456, 0, 0.9877715582939078, 0]

The value is NaN.
[  2.5617105  -20.0678941   -9.27384134]


[0.9914884252410378, 0, 0.9914883033822394, 0]

The value is NaN.
[  2.75019311 -20.05360145  -9.27236871]


[0.9951970357124741, 0, 0.9951970325885041, 0]

The value is NaN.
[  2.93870537 -20.03796144  -9.27027887]


[0.9989000488044383, 0, 0.9989000404648569, 0]

The value is NaN.
[  3.12723774 -20.0209718   -9.26757052]


[1.0025531912651804, 0, 1.0025530215897511, 0]

[54.06128642079847, 143.6970552764372]
TODO LamberSolverA
[  3.31578063 -20.00263027  -9.26424237]


[1.0062428599688449, 0, 1.0062421163046043, 0]

[54.02988565243891, 91.09673343040458]
TODO LamberSolverA
[  3.5043244  -19.98293464  -9.26029314]


[0, 0.9929675662088031, 0, 0.9929656557208061]

The value is NaN.
[  3.69285935 -19.9618827   -9.25572156]


[0, 0.9965825033075938, 0, 0.9965785045036201]

The value is NaN.
[  3.88137573 -19.93947227  -9.25052636]


[0, 1.0001497312130332, 0, 1.0001428342936862]

[54.1650011870623, 55.821802822826484]
TODO LamberSolverA
[  4.06986374 -19.91570122  -9.24470629]


[0, 1.003753005445037, 0, 1.0037410767984507]

[54.165571431319634, 53.19442259498537]
TODO LamberSolverA
[  4.25831351 -19.8905674   -9.23826011]


[0, 1.0073501321170257, 0, 1.007331794273456]

[54.164427299526665, 51.76271871749812]
TODO LamberSolverA
[  4.44671514 -19.86406873  -9.2311866 ]


[0, 1.0109413488605454, 0, 1.0109146497209855]

[54.165138276223814, 50.97626859239554]
TODO LamberSolverA
[  4.63505865 -19.83620312  -9.22348452]


[0, 1.0145275278345527, 0, 1.0144902303596832]

[54.16742288906117, 50.55233119419786]
TODO LamberSolverA
[  4.82333403 -19.80696853  -9.21515267]


[0, 1.0181084602250225, 0, 1.0180580483594333]

[54.170923054555615, 50.33879908279127]
TODO LamberSolverA
[  5.01153118 -19.77636294  -9.20618985]


[0, 1.0216845205293115, 0, 1.0216181946716574]

[54.175358945375805, 50.250603342378945]
TODO LamberSolverA
[  5.19963998 -19.74438436  -9.19659487]


[0, 1.025255639312474, 0, 1.0251703137686337]

[54.18052646671943, 50.23846813490924]
TODO LamberSolverA
[  5.38765023 -19.71103081  -9.18636657]


[0, 1.0288218530335795, 0, 1.028714151677664]

[54.186276315802445, 50.27296054009531]
TODO LamberSolverA
[  5.57555167 -19.67630038  -9.17550376]


[0, 1.0323839139119648, 0, 1.0322501623652451]

[54.19249710420141, 50.33603654636218]
TODO LamberSolverA
[  5.763334   -19.64019113  -9.1640053 ]


[0, 1.0359419399996608, 0, 1.035777509721939]

[54.19910635746109, 50.41639589056129]
TODO LamberSolverA
[  5.95098683 -19.60270121  -9.15187005]


[0, 1.0394954260081755, 0, 1.0392973470571572]

[54.206042312749894, 50.50684313635969]
TODO LamberSolverA
[  6.13849973 -19.56382877  -9.13909689]


[0, 1.0430451825092826, 0, 1.0428075597804796]

[54.21325558526506, 50.60274196326321]
TODO LamberSolverA
[  6.3258622  -19.52357199  -9.12568468]


[0, 1.0465907297499026, 0, 1.0463099635306117]

[54.220709230822365, 50.7010842322175]
TODO LamberSolverA
[  6.51306369 -19.48192908  -9.11163235]


[0, 1.0501335493056367, 0, 1.0498037556055246]

[54.22837177915418, 50.79991639679115]
TODO LamberSolverA
[  6.70009358 -19.43889831  -9.09693879]


[0, 1.0536725218176273, 0, 1.0532881520190456]

[54.236220987719534, 50.897977570231525]
TODO LamberSolverA
[  6.88694116 -19.39447796  -9.08160294]


[0, 1.0572091350069883, 0, 1.0567636560350648]

[54.24423620228211, 50.99446687454618]
TODO LamberSolverA
[  7.0735957  -19.34866635  -9.06562372]


[0, 1.0607422934630184, 0, 1.060230125952287]

[54.25240315775301, 51.08889184612878]
TODO LamberSolverA
[  7.26004638 -19.30146184  -9.04900011]


[0, 1.0642728404296082, 0, 1.0636874176705688]

[54.260708364767154, 51.18096774623936]
TODO LamberSolverA
[  7.44628231 -19.25286281  -9.03173106]


[0, 1.0678009795316032, 0, 1.0671353846473617]

[54.269141253380056, 51.27055002137195]
TODO LamberSolverA
[  7.63229254 -19.20286771  -9.01381557]


[0, 1.071326277804256, 0, 1.0705738778883533]

[54.27769360738286, 51.35758857001892]
TODO LamberSolverA
[  7.81806606 -19.15147501  -8.99525264]


[0, 1.0748502313135495, 0, 1.074002745960434]

[54.286357051621195, 51.442096411015285]
TODO LamberSolverA
[  8.00359177 -19.09868322  -8.97604128]


[0, 1.0783724094520988, 0, 1.077421200290197]

[54.29512603388669, 51.52412827141285]
TODO LamberSolverA
[  8.18885853 -19.04449088  -8.95618053]


[0, 1.0818930294614493, 0, 1.0808303632335574]

[54.303995402279476, 51.60376540403979]
TODO LamberSolverA
[  8.3738551  -18.9888966   -8.93566945]


[0, 1.0854116819248603, 0, 1.0842287975145308]

[54.31296123483422, 51.68110593025983]
TODO LamberSolverA
[  8.5585702  -18.93189901  -8.9145071 ]


[0, 1.0889298623607293, 0, 1.0876176232861239]

[54.322018908028554, 51.75625705214078]
TODO LamberSolverA
[  8.74299246 -18.87349679  -8.89269257]


[0, 1.0924465303412292, 0, 1.0909953977419686]

[54.33116600575422, 51.82933080082215]
TODO LamberSolverA
[  8.92711045 -18.81368868  -8.87022497]


[0, 1.0959631896747428, 0, 1.0943632290196856]

[54.340398866790466, 51.900440039785394]
TODO LamberSolverA
[  9.11091265 -18.75247344  -8.84710344]


[0, 1.099478811276992, 0, 1.097719675506532]

[54.34971567412005, 51.96969671778949]
TODO LamberSolverA
[  9.29438748 -18.6898499   -8.82332711]


[0, 1.1029949013895182, 0, 1.101065824805884]

[54.35911336933914, 52.03720975477388]
TODO LamberSolverA
[  9.4775233  -18.62581692  -8.79889515]


[0, 1.106510448958393, 0, 1.1044002419699457]

[54.36859050492666, 52.103084570116614]
TODO LamberSolverA
[  9.66030837 -18.56037344  -8.77380675]


[0, 1.1100263326176878, 0, 1.107723367957472]

[54.37814476603958, 52.16742200271198]
TODO LamberSolverA
[  9.8427309  -18.49351841  -8.74806113]


[0, 1.113543440838255, 0, 1.1110350139046903]

[54.38777399126735, 52.2303181939917]
TODO LamberSolverA
[ 10.02477901 -18.42525087  -8.72165752]


[0, 1.1170607797793535, 0, 1.114335611431246]

[54.397477095398195, 52.29186437616483]
TODO LamberSolverA
[ 10.20644074 -18.35556988  -8.69459516]


[0, 1.1205792426716958, 0, 1.117623712582313]

[54.407252128748254, 52.35214705902901]
TODO LamberSolverA
[ 10.38770408 -18.2844746   -8.66687334]


[0, 1.1240997273738198, 0, 1.1208997354601113]

[54.41709732736273, 52.41124782196486]
TODO LamberSolverA
[ 10.56855692 -18.21196419  -8.63849136]


[0, 1.1276212674434127, 0, 1.1241634700752625]

[54.42701177296372, 52.46924362439211]
TODO LamberSolverA
[ 10.74898708 -18.13803791  -8.60944854]


[0, 1.1311447679123816, 0, 1.1274147008921935]

[54.43699383295984, 52.5262070293731]
TODO LamberSolverA
[ 10.92898231 -18.06269507  -8.57974425]


[0, 1.1346705193505968, 0, 1.1306532067440522]

[54.44704221952136, 52.5822063870786]
TODO LamberSolverA
[ 11.10853027 -17.98593503  -8.54937784]


[0, 1.1381994367506036, 0, 1.133878760758196]

[54.45715546044231, 52.63730605677367]
TODO LamberSolverA
[ 11.28761855 -17.90775721  -8.51834873]


[0, 1.1417305892699694, 0, 1.1370911302690725]

[54.467332851657545, 52.69156666513216]
TODO LamberSolverA
[ 11.46623467 -17.82816111  -8.48665635]


[0, 1.1452649018525645, 0, 1.1402900767472826]

[54.47757304770763, 52.745045356785795]
TODO LamberSolverA
[ 11.64436605 -17.74714628  -8.45430014]


[0, 1.1488026908163722, 0, 1.1434753557088537]

[54.48787497059835, 52.79779598524803]
TODO LamberSolverA
[ 11.82200005 -17.66471234  -8.4212796 ]


[0, 1.1523442794100383, 0, 1.1466473277308908]

[54.498237602984275, 52.84986932033577]
TODO LamberSolverA
[ 11.99912395 -17.58085899  -8.38759425]


[0, 1.1558906083633667, 0, 1.1498045126877365]

[54.50865978708524, 52.901313459639915]
TODO LamberSolverA
[ 12.17572493 -17.49558597  -8.35324361]


[0, 1.159440796402245, 0, 1.152946651958812]

[54.51914096917605, 52.952173719308576]
TODO LamberSolverA
[ 12.35179012 -17.40889311  -8.31822727]


[0, 1.1629957969545734, 0, 1.1560746948878862]

[54.52968007793838, 53.002492890337805]
TODO LamberSolverA
[ 12.52730655 -17.32078031  -8.28254484]


[0, 1.1665559624703037, 0, 1.1591877570486029]

[54.540276283893725, 53.0523116087284]
TODO LamberSolverA
[ 12.70226116 -17.23124755  -8.24619594]


[0, 1.170121652846695, 0, 1.1622855579873903]

[54.5509288135448, 53.1016683194467]
TODO LamberSolverA
[ 12.87664084 -17.14029487  -8.20918024]


[0, 1.1736932354387621, 0, 1.1653678117534971]

[54.56163696187785, 53.15059948291941]
TODO LamberSolverA
[ 13.05043237 -17.04792239  -8.17149744]


[0, 1.1772716859983485, 0, 1.1684342271197348]

[54.57239990730599, 53.19913969296914]
TODO LamberSolverA
[ 13.22362247 -16.95413032  -8.13314729]


[0, 1.1808561868387133, 0, 1.1714845076858051]

[54.583217382327504, 53.247321856905266]
TODO LamberSolverA
[ 13.39619777 -16.85891894  -8.09412954]


[0, 1.1844477283658332, 0, 1.174518351664537]

[54.59408864241064, 53.295177314772374]
TODO LamberSolverA
[ 13.56814481 -16.76228862  -8.05444401]


[0, 1.1880467105925367, 0, 1.1775354513732381]

[54.60501310213667, 53.342736004736636]
TODO LamberSolverA
[ 13.73945005 -16.66423979  -8.01409052]


[0, 1.191653543563851, 0, 1.180535492402767]

[54.61599012321723, 53.390026599987124]
TODO LamberSolverA
[ 13.91009989 -16.564773    -7.97306897]


[0, 1.1952686483830974, 0, 1.1835181526811476]

[54.627019039660574, 53.43707669625491]
TODO LamberSolverA
[ 14.08008063 -16.46388885  -7.93137926]


[0, 1.198893048472498, 0, 1.1864831015824344]

[54.63809893619431, 53.48391285428997]
TODO LamberSolverA
[ 14.24937848 -16.36158806  -7.88902134]


[0, 1.2025260103419817, 0, 1.1894294083880328]

[54.64922923604118, 53.53056078968848]
TODO LamberSolverA
[ 14.41797958 -16.25787143  -7.84599521]


[0, 1.2061685821049541, 0, 1.1923579093397596]

[54.66040887889404, 53.57704525570217]
TODO LamberSolverA
[ 14.58586999 -16.15273984  -7.80230091]


[0, 1.2098212366684324, 0, 1.1952676499781096]

[54.67163686830287, 53.62339036883124]
TODO LamberSolverA
[ 14.7530357  -16.04619428  -7.75793849]


[0, 1.213484461178851, 0, 1.198158260450904]

[54.68291217173784, 53.669619518223314]
TODO LamberSolverA
[ 14.91946258 -15.93823583  -7.71290809]


[0, 1.2171587574940423, 0, 1.2010293604616573]

[54.694233681269694, 53.715755421516036]
TODO LamberSolverA
[ 15.08513645 -15.82886566  -7.66720985]


[0, 1.2208452238441727, 0, 1.2038805591359287]

[54.70560015383648, 53.76182022740139]
TODO LamberSolverA
[ 15.25004304 -15.71808505  -7.62084397]


[0, 1.2245432323918926, 0, 1.206710872439675]

[54.71701065604978, 53.80783560731234]
TODO LamberSolverA
[ 15.414168   -15.60589538  -7.57381071]


[0, 1.2282539118226796, 0, 1.2095210572320247]

[54.72846388525957, 53.853822632428745]
TODO LamberSolverA
[ 15.57749691 -15.49229813  -7.52611036]


[0, 1.231977828218264, 0, 1.21231010235498]

[54.73995863634963, 53.89980210152966]
TODO LamberSolverA
[ 15.74001524 -15.37729489  -7.47774324]


[0, 1.2357155651971061, 0, 1.2150775723949625]

[54.75149366934028, 53.94579439436916]
TODO LamberSolverA
[ 15.90170841 -15.26088734  -7.42870974]


[0, 1.2394682976118387, 0, 1.2178230202718385]

[54.763067643447854, 53.99181959924308]
TODO LamberSolverA
[ 16.06256174 -15.1430773   -7.37901031]


[0, 1.2432355022703296, 0, 1.2205454127078748]

[54.774679508366006, 54.03789759939036]
TODO LamberSolverA
[ 16.22256049 -15.02386667  -7.3286454 ]


[0, 1.247018390231347, 0, 1.2232454331625886]

[54.78632790555676, 54.08404793549947]
TODO LamberSolverA
[ 16.38168983 -14.90325747  -7.27761557]


[0, 1.2508176218066118, 0, 1.2259220187446416]

[54.79801157072018, 54.13029012354262]
TODO LamberSolverA
[ 16.53993485 -14.78125186  -7.22592138]


[0, 1.2546338781562203, 0, 1.2285746741504655]

[54.809729256418635, 54.176643540727255]
TODO LamberSolverA
[ 16.69728056 -14.65785208  -7.17356346]


[0, 1.258468430196445, 0, 1.2312023223639366]

[54.82147961047834, 54.22312752241527]
TODO LamberSolverA
[ 16.8537119  -14.53306051  -7.12054251]


[0, 1.2623208693107688, 0, 1.2338055879399126]

[54.83326157042295, 54.269761265173386]
TODO LamberSolverA
[ 17.00921373 -14.40687963  -7.06685925]


[0, 1.2661925085620112, 0, 1.2363833631723706]

[54.845073814976544, 54.31656410733646]
TODO LamberSolverA
[ 17.16377083 -14.27931207  -7.01251448]


[0, 1.2700846793007654, 0, 1.2389351035431375]

[54.85691507234702, 54.363555409563546]
TODO LamberSolverA
[ 17.31736791 -14.15036056  -6.95750904]


[0, 1.2739970581745785, 0, 1.2414596905317659]

[54.86878433447244, 54.41075465538231]
TODO LamberSolverA
[ 17.4699896  -14.02002797  -6.90184382]


[0, 1.277931020423964, 0, 1.2439576879009817]

[54.88068040331548, 54.45818130069072]
TODO LamberSolverA
[ 17.62162043 -13.88831728  -6.84551978]


[0, 1.2818879626662514, 0, 1.2464279493817745]

[54.89260210810045, 54.50585504748152]
TODO LamberSolverA
[ 17.7722449  -13.75523161  -6.78853795]


[0, 1.2858676454015578, 0, 1.2488693273728735]

[54.90454858600845, 54.55379580390825]
TODO LamberSolverA
[ 17.92184739 -13.62077422  -6.73089937]


[0, 1.2898715109991077, 0, 1.251282351623114]

[54.91651875360371, 54.60202350890897]
TODO LamberSolverA
[ 18.07041223 -13.4849485   -6.6726052 ]


[0, 1.2939010292605784, 0, 1.2536658472819948]

[54.92851154969462, 54.65055854069008]
TODO LamberSolverA
[ 18.21792366 -13.34775798  -6.61365662]


[0, 1.29795605125352, 0, 1.2560191940428418]

[54.940526071321116, 54.699421582194006]
TODO LamberSolverA
[ 18.36436585 -13.20920633  -6.55405488]


[0, 1.3020381057745196, 0, 1.2583412071040176]

[54.95256113958341, 54.74863384294791]
TODO LamberSolverA
[ 18.50972289 -13.06929736  -6.49380131]


[0, 1.306148761547765, 0, 1.260632341158042]

[54.96461547365411, 54.7982169536195]
TODO LamberSolverA
[ 18.65397882 -12.92803504  -6.43289729]


[0, 1.31028798369364, 0, 1.2628908158725596]

[54.97668789789601, 54.84819345208365]
TODO LamberSolverA
[ 18.79711759 -12.78542347  -6.37134427]


[0, 1.314457963250442, 0, 1.2651170521220332]

[54.988776852064646, 54.89858640642098]
TODO LamberSolverA
[ 18.93912309 -12.64146692  -6.30914377]


[0, 1.3186587631795363, 0, 1.267309777575709]

[55.00088094146727, 54.94941988950687]
TODO LamberSolverA
[ 19.07997913 -12.49616981  -6.24629738]


[0, 1.3228926567940578, 0, 1.2694677112133188]

[55.0129984387538, 55.000718862977436]
TODO LamberSolverA
[ 19.21966947 -12.3495367   -6.18280677]


[0, 1.3271598104369666, 0, 1.2715911984515698]

[55.02512778346784, 55.05250909103049]
TODO LamberSolverA
[ 19.3581778  -12.20157234  -6.11867365]


[0, 1.3314625898967147, 0, 1.273678906556295]

[55.03726714244708, 55.10481754456916]
TODO LamberSolverA
[ 19.49548776 -12.05228162  -6.05389983]


[0, 1.3358012707935845, 0, 1.275729494603552]

[55.04941484990846, 55.15767230841762]
TODO LamberSolverA
[ 19.6315829  -11.90166959  -5.9884872 ]


[0, 1.340178323273429, 0, 1.277743226823504]

[55.061568951876914, 55.211102467331955]
TODO LamberSolverA
[ 19.76644674 -11.74974147  -5.92243769]


[0, 1.3445946692628576, 0, 1.2797181672118592]

[55.07372764062511, 55.2651386501622]
TODO LamberSolverA
[ 19.90006274 -11.59650266  -5.85575333]


[0, 1.3490513083163795, 0, 1.2816545328484719]

[55.085889063690715, 55.31981265096262]
TODO LamberSolverA
[ 20.03241428 -11.4419587   -5.78843622]


[0, 1.3535508779892185, 0, 1.283550878179499]

[55.09805115396837, 55.37515790615949]
TODO LamberSolverA
[ 20.16348472 -11.28611533  -5.72048855]


[0, 1.3580945027352787, 0, 1.2854057493792228]

[55.11021200094909, 55.43120951537406]
TODO LamberSolverA
[ 20.29325733 -11.12897845  -5.65191256]


[0, 1.3626833897030597, 0, 1.2872192693319757]

[55.12236962331191, 55.48800409754346]
TODO LamberSolverA
[ 20.42171537 -10.97055414  -5.5827106 ]


[0, 1.367320380072595, 0, 1.2889893928741403]

[55.13452191713303, 55.54558042961952]
TODO LamberSolverA
[ 20.54884201 -10.81084865  -5.51288508]


[0, 1.3720068278911832, 0, 1.2907161871175419]

[55.146666862032575, 55.603979010415216]
TODO LamberSolverA
[ 20.67462041 -10.64986843  -5.4424385 ]


[0, 1.3767446931700489, 0, 1.2923975558945147]

[55.15880242061523, 55.66324279854621]
TODO LamberSolverA
[ 20.79903365 -10.48762009  -5.37137344]


[0, 1.381535508867207, 0, 1.2940335080853265]

[55.170926553749894, 55.72341677239655]
TODO LamberSolverA
[ 20.92206479 -10.32411045  -5.29969256]


[0, 1.38638244011776, 0, 1.295621897431214]

[55.18303713414244, 55.78454869669601]
TODO LamberSolverA
[ 21.04369684 -10.15934649  -5.22739862]


[0, 1.391287199019485, 0, 1.2971626733957216]

[55.19513215426855, 55.84668871176773]
TODO LamberSolverA
[21.16391277 -9.9933354  -5.15449445]


[0, 1.3962521122040417, 0, 1.2986536423345207]

[55.20720959381313, 55.90989009100504]
TODO LamberSolverA
[21.28269551 -9.82608455 -5.08098298]


[0, 1.401279607350125, 0, 1.3000946953380044]

[55.219267469626494, 55.974208870006116]
TODO LamberSolverA
[21.40002796 -9.65760153 -5.00686722]


[0, 1.4063722168289787, 0, 1.3014835968414373]

[55.23130383882594, 56.03970461231842]
TODO LamberSolverA
[21.51589299 -9.4878941  -4.93215026]


[0, 1.411532581844682, 0, 1.302820182755489]

[55.24331681013376, 56.106440058880096]
TODO LamberSolverA
[21.63027344 -9.31697023 -4.85683531]


[0, 1.416763457484922, 0, 1.3041021814988638]

[55.255304529084945, 56.174481962085295]
TODO LamberSolverA
[21.7431521  -9.14483809 -4.78092565]


[0, 1.4220682172158448, 0, 1.305328856645797]

[55.26726510000792, 56.24390084747314]
TODO LamberSolverA
[21.85451175 -8.97150607 -4.70442465]


[0, 1.4274488737241462, 0, 1.3064994512195265]

[55.27919672172571, 56.31477164167044]
TODO LamberSolverA
[21.96433517 -8.79698274 -4.62733579]


[0, 1.4329090744654467, 0, 1.3076116166737743]

[55.29109744656846, 56.387174384835156]
TODO LamberSolverA
[22.07260507 -8.6212769  -4.54966264]


[0, 1.4384521269918005, 0, 1.308665041970248]

[55.30296520817146, 56.46119412281952]
TODO LamberSolverA
[22.17930419 -8.44439756 -4.47140886]


[0, 1.4440820004130293, 0, 1.3096573171912813]

[55.31479782388353, 56.5369222290536]
TODO LamberSolverA
[22.28441523 -8.26635393 -4.39257822]


[0, 1.449801385859785, 0, 1.3105875254306385]

[55.32659303349412, 56.61445637127912]
TODO LamberSolverA
[22.38792088 -8.08715545 -4.31317457]


[0, 1.4556146388623585, 0, 1.3114541915688154]

[55.33834834732789, 56.69390150962505]
TODO LamberSolverA
[22.48980383 -7.90681178 -4.23320188]


[0, 1.4615263297002163, 0, 1.3122563053327188]

[55.35006115817386, 56.77537040581919]
TODO LamberSolverA
[22.59004675 -7.7253328  -4.15266421]


[0, 1.4675398027469027, 0, 1.312991266686261]

[55.361728810287424, 56.85898470594034]
TODO LamberSolverA
[22.68863233 -7.54272859 -4.07156572]


[0, 1.4736605828522809, 0, 1.3136579597338534]

[55.37334845131137, 56.94487522825263]
TODO LamberSolverA
[22.78554324 -7.35900949 -3.98991069]


[0, 1.4798930049193275, 0, 1.314255210904426]

[55.3849171943165, 57.033183088646396]
TODO LamberSolverA
[22.88076216 -7.17418605 -3.90770348]


[0, 1.4862416982373396, 0, 1.3147802750484725]

[55.396432057454064, 57.1240610384186]
TODO LamberSolverA
[22.97427179 -6.98826904 -3.82494858]


[0, 1.4927130147210832, 0, 1.3152318645949996]

[55.40788990062086, 57.21767401677533]
TODO LamberSolverA
[23.06605482 -6.80126949 -3.74165057]


[0, 1.4993122022486811, 0, 1.3156081288286143]

[55.419287545756546, 57.31420078678728]
TODO LamberSolverA
[23.15609397 -6.61319865 -3.65781415]


[0, 1.5060453351342828, 0, 1.3159071550920207]

[55.43062170727478, 57.413835314348276]
TODO LamberSolverA
[23.24437197 -6.42406798 -3.57344411]


[0, 1.512918863392983, 0, 1.3161269661465131]

[55.441888995011126, 57.516788361082334]
TODO LamberSolverA
[23.33087158 -6.23388923 -3.48854536]


[0, 1.5199396426056146, 0, 1.3162655173175666]

[55.45308593276167, 57.623289326683775]
TODO LamberSolverA
[23.41557558 -6.04267434 -3.40312294]


[0, 1.5271149661610366, 0, 1.3163211913247435]

[55.46420894537073, 57.733588162549346]
TODO LamberSolverA
[23.49846678 -5.85043552 -3.31718196]


[0, 1.5344530591931467, 0, 1.3162908054964915]

[55.47525435236841, 57.84795816814065]
TODO LamberSolverA
[23.57952803 -5.65718522 -3.23072769]


[0, 1.5419612819711697, 0, 1.3161725954846328]

[55.486218459577856, 57.96669789332867]
TODO LamberSolverA
[23.65874221 -5.46293613 -3.14376548]


[0, 1.5496489210240363, 0, 1.3159642227549218]

[55.4970974300884, 58.09013454618601]
TODO LamberSolverA
[23.73609224 -5.2677012  -3.0563008 ]


[0, 1.5575258572574369, 0, 1.3156632705588562]

[55.50788736210802, 58.21862723066316]
TODO LamberSolverA
[23.81156109 -5.07149361 -2.96833924]


[0, 1.5656017029178184, 0, 1.3152672424881509]

[55.51858433745119, 58.352570759850266]
TODO LamberSolverA
[23.8851318  -4.87432681 -2.87988652]


[0, 1.5738867837444768, 0, 1.314773073323385]

[55.52918440418385, 58.49240016172878]
TODO LamberSolverA
[23.95678742 -4.67621449 -2.79094846]


[0, 1.5823935238414326, 0, 1.3141790833114186]

[55.53968346546223, 58.63859501618386]
TODO LamberSolverA
[24.02651111 -4.4771706  -2.70153101]


[0, 1.5911338236909225, 0, 1.313482040298871]

[55.550077484516365, 58.7916861002242]
TODO LamberSolverA
[24.09428606 -4.27720934 -2.61164021]


[0, 1.6001213683159239, 0, 1.3126791192125429]

[55.56036230679615, 58.95226131833539]
TODO LamberSolverA
[24.16009554 -4.07634518 -2.52128226]


[0, 1.6093694997605132, 0, 1.311767409336721]

[55.57053377637651, 59.12097352137004]
TODO LamberSolverA
[24.22392289 -3.87459284 -2.43046346]


[0, 1.618893949783475, 0, 1.3107434277905678]

[55.5805875958132, 59.29854958384166]
TODO LamberSolverA
[24.28575154 -3.67196729 -2.33919024]


[0, 1.628711625766644, 0, 1.3096050480302808]

[55.59051934982256, 59.485800248454225]
TODO LamberSolverA
[24.34556498 -3.46848379 -2.24746913]


[0, 1.638839872733017, 0, 1.3083485775572974]

[55.600324446833355, 59.683633534662725]
TODO LamberSolverA
[24.40334682 -3.26415784 -2.15530682]


[0, 1.6492979364383396, 0, 1.3069702108091625]

[55.6099980689605, 59.89306908020127]
TODO LamberSolverA
[24.45908073 -3.05900521 -2.06271009]


[0, 1.660106695946218, 0, 1.305467446643957]

[55.61953506726449, 60.11525500922662]
TODO LamberSolverA
[24.51275049 -2.85304193 -1.96968587]


[0, 1.6712888595665856, 0, 1.3038361775167684]

[55.628929964239006, 60.35148988789139]
TODO LamberSolverA
[24.56434001 -2.64628431 -1.87624119]


[0, 1.6828696064772726, 0, 1.3020721387292056]

[55.63817692592785, 60.60324694007585]
TODO LamberSolverA
[24.61383327 -2.43874892 -1.78238323]


[0, 1.6948755711264925, 0, 1.3001718180937527]

[55.64726971318954, 60.87220304943382]
TODO LamberSolverA
[24.66121438 -2.23045259 -1.68811927]


[0, 1.7073363946483229, 0, 1.298131505983778]

[55.656201680286856, 61.16027455727495]
TODO LamberSolverA
[24.70646758 -2.02141244 -1.59345675]


[0, 1.7202846205890048, 0, 1.295945835925763]

[55.66496576432294, 61.469660700851435]
TODO LamberSolverA
[24.74957722 -1.81164583 -1.4984032 ]


[0, 1.7337560675472223, 0, 1.2936106296626844]

[55.67355443407446, 61.80289406675899]
TODO LamberSolverA
[24.79052779 -1.60117042 -1.40296632]


[0, 1.747790676002009, 0, 1.291121445772331]

[55.68195967109177, 62.16290461953689]
TODO LamberSolverA
[24.82930391 -1.39000413 -1.30715389]


[0, 1.762432188173078, 0, 1.2884721350283919]

[55.69017293233959, 62.55309839450893]
TODO LamberSolverA
[24.86589035 -1.17816513 -1.21097385]


[0, 1.7777283704141504, 0, 1.2856576497629233]

[55.69818511902217, 62.97745232802406]
TODO LamberSolverA
[24.90027202 -0.9656719  -1.11443427]


[0, 1.7937341223692538, 0, 1.2826721204405702]

[55.705986440245184, 63.440635211704226]
TODO LamberSolverA
[24.932434   -0.75254317 -1.01754333]


[0, 1.8105095098609902, 0, 1.2795092874666343]

[55.713566433332076, 63.948157850786465]
TODO LamberSolverA
[24.96236152 -0.53879794 -0.92030935]


[0, 1.828122764963005, 0, 1.2761624559325362]

[55.720913807193135, 64.50656277666795]
TODO LamberSolverA
[24.99003997 -0.32445549 -0.82274079]


[0, 1.846650291876111, 0, 1.2726244423955375]

[55.72801638341701, 65.12366560385018]
TODO LamberSolverA
[25.01545492 -0.10953537 -0.72484622]


[0, 1.8661777560966337, 0, 1.2688870494952174]

[55.73486100964284, 65.8088646308413]
TODO LamberSolverA
[25.03859213  0.10594261 -0.62663435]


[0, 1.8868045411304393, 0, 1.2649428610929807]

[55.74143339023729, 66.57353880307463]
TODO LamberSolverA
[25.05943752  0.32195834 -0.52811401]


[0, 1.9086420433694828, 0, 1.260782355455376]

[55.74771798645328, 67.43157074606286]
TODO LamberSolverA
[25.07797724  0.53849147 -0.42929418]


[0, 1.931819407584391, 0, 1.2563952238082743]

[55.75369785175305, 68.40003101323023]
TODO LamberSolverA
[25.09419759  0.75552137 -0.33018394]


[0, 1.9564852924554044, 0, 1.2517716332336746]

[55.75935436544311, 69.50008706100861]
TODO LamberSolverA
[25.10808512  0.97302714 -0.23079252]


[0, 1.982812039008523, 0, 1.2468988504721827]

[55.76466706521987, 70.7582299079869]
TODO LamberSolverA
[25.11962656  1.1909876  -0.13112928]


[0, 2.0110024114779623, 0, 1.2417643046029125]

[55.76961321997049, 72.20793280809355]
TODO LamberSolverA
[25.12880888  1.40938132 -0.0312037 ]


[0, 2.0412941580403703, 0, 1.236353530120001]

[55.77416750059255, 73.89193941529196]
TODO LamberSolverA
[25.13561924  1.62818661  0.06897462]


[0, 2.0739703024565634, 0, 1.2306503575470387]

[55.77830136780578, 75.8654500614608]
TODO LamberSolverA
[25.14004507  1.8473815   0.16939594]


[0, 2.109370403655223, 0, 1.2246365698396762]

[55.781982467277885, 78.20062936299782]
TODO LamberSolverA
[25.14207401  2.06694377  0.2700504 ]


[0, 2.147906843222047, 0, 1.2182914597777719]

[55.78517366685837, 80.99308484329858]
TODO LamberSolverA
[25.14169394  2.28685091  0.37092801]


[0, 2.190083970435579, 0, 1.2115907935899874]

[55.78783194101608, 84.37135130795224]
TODO LamberSolverA
[25.13889299  2.5070802   0.47201866]


[0, 2.236530459581716, 0, 1.2045078745941717]

[55.789906795905075, 88.51106223031829]
TODO LamberSolverA
[25.13365956  2.72760861  0.5733121 ]


[0, 2.288039199942275, 0, 1.1970092857131374]

[55.79133823331152, 93.65667259165896]
TODO LamberSolverA
[25.12598229  2.94841289  0.67479797]


[0, 2.3456295018739177, 0, 1.1890566680746049]

[55.79205385967688, 100.15570913750427]
TODO LamberSolverA
[25.11585009  3.16946951  0.77646579]


[0, 2.4106381416489238, 0, 1.1806024056052085]

[55.791964930883, 108.51477295265808]
TODO LamberSolverA
[25.10325216  3.39075469  0.87830493]


[0, 2.484862291814342, 0, 1.1715890061065193]

[55.79096060470418, 119.49510150349076]
TODO LamberSolverA
[25.08817794  3.61224441  0.98030467]


[0, 2.5707892088482973, 0, 1.161941477505053]

[55.788899262414404, 134.28447456447302]
TODO LamberSolverA
[25.07061721  3.83391439  1.08245414]


[0, None, 0, 1.1515637242254242]

TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'