In [15]:
### Benjamin Tollison ###
import sympy as sp
from IPython.display import display, Math, Latex
from sympy.solvers.solveset import linsolve
from sympy.solvers.pde import pdsolve
from sympy import  lambdify, Matrix,sin,cos, sinh, cosh, exp, pi, symbols, integrate, Function, Eq
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy
def displayEquations(LHS,RHS):
    left = sp.latex(LHS)
    right = sp.latex(RHS)
    display(Math(left + '=' + right))
    np.set_printoptions(suppress=True)

In [16]:
alpha_symbol,beta_symbol = symbols('\\alpha \\beta')
displayEquations(alpha_symbol,20)
displayEquations(beta_symbol,10)

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [17]:
degree2rad = np.pi/180
displayEquations('x_stab',100*np.cos(10*degree2rad)*np.cos(10*degree2rad))
displayEquations('y_stab',-100*np.sin(20*degree2rad))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [18]:
beta = 10*degree2rad
alpha = 20*degree2rad
z_rotation = np.array([[np.cos(beta),np.sin(beta),0],
                       [-np.sin(beta),np.cos(beta),0],
                       [0,0,1]])
y_rotation = np.array([[np.cos(alpha),0,np.sin(alpha)],
                       [0,1,0],
                       [-np.sin(alpha),0,np.cos(alpha)]])
v_body = np.matmul(np.linalg.inv(np.matmul(z_rotation,y_rotation)),np.array([100,0,0]))
displayEquations('v_v',v_body)

<IPython.core.display.Math object>

In [22]:
r_I = np.array([-5000,-8000,-2100])
v_I = np.array([-4,4,-3])
h = np.cross(r_I,v_I)
h_cross_r = np.cross(h,r_I)
displayEquations('h',h)
displayEquations('x_L',h_cross_r/np.linalg.norm(h_cross_r))
displayEquations('y_L',-h/np.linalg.norm(h))
displayEquations('z_L',-r_I/np.linalg.norm(r_I))
dcm = np.array([h_cross_r/np.linalg.norm(h_cross_r),-h/np.linalg.norm(h),-r_I/np.linalg.norm(r_I)])
print(dcm)

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

[[-0.67521486  0.55079694 -0.49061964]
 [-0.52578284  0.10710391  0.84384901]
 [ 0.51733674  0.82773878  0.21728143]]
